{% set name = "xibs" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xibs-{{ version }}.tar.gz
  sha256: 561cb89ea9adcf4ba124846ebee7133cf4fca3a9e6ce89d5c07176d9f007d6dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - scipy >=1.8

test:
  imports:
    - xibs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fsoubelet/xibs
  summary: Prototype Intra-Beam Scattering implementation for Xsuite.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://fsoubelet.github.io/xibs/

extra:
  recipe-maintainers:
    - fsoubelet
