{% set name = "xibs" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xibs-{{ version }}.tar.gz
  sha256: a206f6afce393f974da936461709a03bb0bfcad26824a790065c55a9f23e2532

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - scipy >=1.8

test:
  imports:
    - xibs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fsoubelet/xibs
  summary: Prototype Intra-Beam Scattering implementation for Xsuite.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://fsoubelet.github.io/xibs/

extra:
  recipe-maintainers:
    - fsoubelet
